const products=[
{id:'hc-starter',name:'HyperCore Starter',cat:'PC Gamer',price:2499,level:'Entrada',cpu:'Ryzen 5 5600G',gpu:'Radeon integrada',ram:'16 GB',ssd:'500 GB NVMe',tag:'Custo-benefício'},
{id:'hc-pro',name:'HyperCore Pro',cat:'PC Gamer',price:4499,level:'Intermediário',cpu:'Ryzen 5 7600',gpu:'RTX 5060',ram:'16 GB DDR5',ssd:'1 TB NVMe',tag:'Mais vendido'},
{id:'hc-elite',name:'HyperCore Elite',cat:'PC Gamer',price:6999,level:'Alto desempenho',cpu:'Ryzen 7 7800X3D',gpu:'RTX 5070',ram:'32 GB DDR5',ssd:'2 TB NVMe',tag:'Performance'},
{id:'hc-extreme',name:'HyperCore Extreme',cat:'PC Gamer',price:11999,level:'Extreme',cpu:'Ryzen 9 9950X3D',gpu:'RTX 5090',ram:'64 GB DDR5',ssd:'4 TB NVMe',tag:'Máximo desempenho'},
{id:'office',name:'HyperCore Office',cat:'Trabalho',price:2199,level:'Produtividade',cpu:'Ryzen 5',gpu:'Integrada',ram:'16 GB',ssd:'512 GB NVMe',tag:'Trabalho e estudo'},
{id:'creator',name:'HyperCore Creator',cat:'Workstation',price:7499,level:'Profissional',cpu:'Ryzen 9',gpu:'RTX 5070',ram:'64 GB',ssd:'2 TB NVMe',tag:'Criadores'}
];
const hardware = [
    { name: 'Ryzen 7 7800X3D', cat: 'Processadores', price: 2199, image: 'assets/hardware/ryzen.jpg' },
    { name: 'RTX 5070 12 GB', cat: 'Placas de vídeo', price: 4999, image: 'assets/hardware/rtx5070.jpg' },
    { name: '32 GB DDR5 6000', cat: 'Memórias', price: 699, image: 'assets/hardware/memoria.jpg' },
    { name: 'SSD NVMe 1 TB', cat: 'Armazenamento', price: 449, image: 'assets/hardware/ssd.jpg' },
    { name: 'Fonte 750W 80 Plus Gold', cat: 'Fontes', price: 599, image: 'assets/hardware/fonte.jpg' },
    { name: 'Placa-mãe B650', cat: 'Placas-mãe', price: 999, image: 'assets/hardware/placamae.jpg' },
    { name: 'Gabinete Airflow', cat: 'Gabinetes', price: 399, image: 'assets/hardware/gabinete.jpg' },
    { name: 'Water Cooler 240mm', cat: 'Refrigeração', price: 499, image: 'assets/hardware/cooler.jpg' }
];
const peripherals = [
    { name: 'Teclado Mecânico RGB', cat: 'Teclados', price: 349, image: 'assets/perifericos/teclado.jpg' },
    { name: 'Mouse Gamer RGB', cat: 'Mouses', price: 199, image: 'assets/perifericos/mouse.jpg' },
    { name: 'Headset Gamer 7.1', cat: 'Headsets', price: 299, image: 'assets/perifericos/fone.jpg' },
    { name: 'Monitor Gamer 24"', cat: 'Monitores', price: 899, image: 'assets/perifericos/monitor.jpg' },
    { name: 'Mousepad RGB', cat: 'Mousepads', price: 149, image: 'assets/perifericos/pad.jpg' },
    { name: 'Webcam Full HD', cat: 'Webcams', price: 249, image: 'assets/perifericos/webcam.jpg' },
    { name: 'Microfone USB', cat: 'Microfones', price: 399, image: 'assets/perifericos/microfone.jpg' },
    { name: 'Controle Gamer', cat: 'Controles', price: 299, image: 'assets/perifericos/controle.jpg' }
];
let cart=JSON.parse(localStorage.getItem('hc_cart')||'[]');
const brl=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function saveCart(){localStorage.setItem('hc_cart',JSON.stringify(cart));updateCartCount()}
function updateCartCount(){const n=cart.reduce((a,x)=>a+x.qty,0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=n)}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function addCart(item){const p=cart.find(x=>x.id===item.id);p?p.qty++:cart.push({...item,qty:1});saveCart();toast(`${item.name} adicionado ao carrinho.`)}
function productCard(p){return `<article class="card product"><div class="product-img">
${p.image ? `<img src="${p.image}" alt="${p.name}" class="product-photo">` : `<div class="pc"></div>`}
</div><div class="product-body"><div class="tags"><span class="tag">${p.tag||p.cat}</span>${p.level?`<span class="tag">${p.level}</span>`:''}</div><h3>${p.name}</h3><p class="muted">${p.cpu||p.cat} • ${p.gpu||''}</p>${p.ram?`<p class="muted">${p.ram} • ${p.ssd}</p>`:''}<div class="price">${brl(p.price)}</div><div class="actions"><button class="btn primary" onclick='addCart(${JSON.stringify(p)})'>Comprar</button><a class="btn ghost" href="produto.html?id=${p.id}">Detalhes</a></div></div></article>`}
function renderProducts(list,selector){const el=document.querySelector(selector);if(el)el.innerHTML=list.map(productCard).join('')||'<div class="empty">Nenhum produto encontrado.</div>'}
function renderGenericProducts(){renderProducts(products,'#pc-grid');renderProducts(hardware.map((x,i)=>({...x,id:'hw'+i,tag:'Hardware'})),'#hardware-grid');renderProducts(peripherals.map((x,i)=>({...x,id:'per'+i,tag:'Periférico'})),'#peripheral-grid')}
function initFilters(){document.querySelectorAll('[data-filter-target]').forEach(input=>input.addEventListener('input',e=>{const q=e.target.value.toLowerCase();const target=e.target.dataset.filterTarget;const base=target==='pc'?products:target==='hardware'?hardware.map((x,i)=>({...x,id:'hw'+i,tag:'Hardware'})):peripherals.map((x,i)=>({...x,id:'per'+i,tag:'Periférico'}));renderProducts(base.filter(p=>JSON.stringify(p).toLowerCase().includes(q),'#'+(target==='pc'?'pc-grid':target==='hardware'?'hardware-grid':'peripheral-grid')))}))}
function renderCart(){const box=document.querySelector('#cart-items'),summary=document.querySelector('#cart-summary');if(!box)return;if(!cart.length){box.innerHTML='<div class="empty">Seu carrinho está vazio.<br><a class="btn primary" href="pcs.html">Explorar PCs</a></div>';if(summary)summary.innerHTML='';return}box.innerHTML=cart.map((x,i)=>`<div class="cart-item"><div><strong>${x.name}</strong><div class="muted">${brl(x.price)} cada</div></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><strong>${x.qty}</strong><button onclick="changeQty(${i},1)">+</button></div><div><strong>${brl(x.price*x.qty)}</strong><br><button class="btn danger" onclick="removeCart(${i})">Remover</button></div></div>`).join('');const total=cart.reduce((a,x)=>a+x.price*x.qty,0);if(summary)summary.innerHTML=`<div class="card"><h3>Resumo</h3><p class="muted">Subtotal</p><div class="price">${brl(total)}</div><p class="muted">Frete calculado no checkout.</p><a class="btn primary" style="width:100%" href="checkout.html">Continuar para pagamento</a></div>`}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);saveCart();renderCart()}
function removeCart(i){cart.splice(i,1);saveCart();renderCart()}
function openModal(id){document.querySelector(id)?.classList.add('show')}
function closeModal(id){document.querySelector(id)?.classList.remove('show')}
function initQuiz(){const q=document.querySelector('#quiz');if(!q)return;let step=0,answers={};const questions=[{title:'Qual será o principal uso?',opts:['🎮 Jogos','📚 Estudos','💼 Trabalho','🎨 Design e edição']},{title:'Qual seu orçamento?',opts:['Até R$ 2.500','R$ 2.500 – R$ 4.000','R$ 4.000 – R$ 7.000','Acima de R$ 7.000']},{title:'Você pretende fazer upgrades?',opts:['Sim','Não','Talvez']}];function draw(){const s=q.querySelector('#quiz-content');const st=q.querySelector('#quiz-steps');st.innerHTML=questions.map((_,i)=>`<div class="step ${i===step?'active':''}">0${i+1} • ${['Uso','Orçamento','Upgrade'][i]}</div>`).join('');if(step<questions.length){s.innerHTML=`<h2>${questions[step].title}</h2><div class="option-grid">${questions[step].opts.map((o,i)=>`<button class="option ${answers[step]===i?'selected':''}" onclick="window.quizChoose(${i})">${o}</button>`).join('')}</div><div style="margin-top:22px"><button class="btn ghost" ${step===0?'disabled':''} onclick="window.quizBack()">Voltar</button></div>`}else{s.innerHTML=quizResult(answers);}}window.quizChoose=i=>{answers[step]=i;step++;draw()};window.quizBack=()=>{step=Math.max(0,step-1);draw()};function quizResult(a){let budget=a[1]??1;let p=budget===0?products[0]:budget===1?products[1]:budget===2?products[2]:products[3];if(a[0]===1||a[0]===2)p=a[0]===1?products[4]:products[5];return `<div class="result"><span class="kicker">Recomendação HyperCore</span><h2>${p.name}</h2><p class="muted">Com base nas suas respostas, essa configuração é um bom ponto de partida para seu perfil.</p><div class="grid grid-2"><div><strong>CPU</strong><br>${p.cpu}</div><div><strong>GPU</strong><br>${p.gpu}</div><div><strong>RAM</strong><br>${p.ram}</div><div><strong>SSD</strong><br>${p.ssd}</div></div><h3>${brl(p.price)}</h3><button class="btn primary" onclick='addCart(${JSON.stringify(p)})'>Adicionar ao carrinho</button> <button class="btn ghost" onclick="location.reload()">Refazer</button></div>`}draw()}
function initBuilder(){const b=document.querySelector('#builder');if(!b)return;const parts=[{key:'cpu',label:'Processador',opts:['Ryzen 5 7600 — R$ 1.299','Ryzen 7 7800X3D — R$ 2.199','Ryzen 9 9950X3D — R$ 4.299']},{key:'gpu',label:'Placa de vídeo',opts:['RTX 5060 — R$ 2.099','RTX 5070 — R$ 4.999','RTX 5090 — R$ 13.999']},{key:'ram',label:'Memória RAM',opts:['16 GB DDR5 — R$ 399','32 GB DDR5 — R$ 699','64 GB DDR5 — R$ 1.299']},{key:'ssd',label:'Armazenamento',opts:['1 TB NVMe — R$ 449','2 TB NVMe — R$ 799','4 TB NVMe — R$ 1.499']},{key:'case',label:'Gabinete',opts:['Airflow — R$ 399','Premium — R$ 699','Showcase — R$ 999']}];let sel={};b.innerHTML=parts.map(p=>`<div class="card"><h3>${p.label}</h3><div class="option-grid">${p.opts.map((o,i)=>`<button class="option" data-key="${p.key}" data-index="${i}">${o}</button>`).join('')}</div></div>`).join('')+'<div class="card"><h2>Resumo da configuração</h2><div id="build-summary" class="notice">Selecione os componentes.</div><button id="add-build" class="btn primary" disabled>Adicionar configuração ao carrinho</button></div>';b.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{b.querySelectorAll(`[data-key="${btn.dataset.key}"]`).forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');sel[btn.dataset.key]=parts.find(x=>x.key===btn.dataset.key).opts[+btn.dataset.index];update()});function update(){let vals=Object.values(sel),sum=vals.reduce((a,v)=>a+Number(v.match(/R\$ ([\d.]+)/)?.[1].replace('.','')||0),0);const ok=vals.length===parts.length;document.querySelector('#build-summary').innerHTML=ok?`<div class="notice ok">✓ Configuração completa e pronta para revisão.</div><p>${vals.join('<br>')}</p><strong>Total: ${brl(sum)}</strong>`:'<div class="notice warn">Escolha todos os componentes para concluir.</div>';const add=document.querySelector('#add-build');add.disabled=!ok;if(ok)add.onclick=()=>addCart({id:'custom-'+Date.now(),name:'HyperCore Custom Build',price:sum,tag:'Configuração personalizada'})}}
function initUpgrade(){const f=document.querySelector('#upgrade-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#upgrade-result').innerHTML='<div class="result"><h3>Diagnóstico preliminar</h3><p>Recomendamos priorizar armazenamento NVMe e memória RAM quando esses componentes forem os principais gargalos. Para uma recomendação precisa, envie a configuração completa para nossa equipe.</p><button class="btn primary" onclick="toast(\'Solicitação enviada para a HyperCore.\')">Solicitar avaliação</button></div>'})}
function initCheckout(){const f=document.querySelector('#checkout-form');if(!f)return;const total=cart.reduce((a,x)=>a+x.price*x.qty,0);document.querySelector('#checkout-total').textContent=brl(total);f.addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return toast('Adicione um produto antes de finalizar.');localStorage.setItem('hc_last_order',JSON.stringify({id:'HC'+Math.floor(Math.random()*90000+10000),total,date:new Date().toLocaleString('pt-BR')}));cart=[];saveCart();document.querySelector('#checkout-success').classList.remove('hidden');f.classList.add('hidden')})}
function initSearch(){const form=document.querySelector('#global-search');if(form)form.addEventListener('submit',e=>{e.preventDefault();const q=form.querySelector('input').value.trim();location.href='buscar.html?q='+encodeURIComponent(q)})}
function initPage(){updateCartCount();renderGenericProducts();initFilters();renderCart();initQuiz();initBuilder();initUpgrade();initCheckout();initSearch();initProductDetail();const params=new URLSearchParams(location.search);const q=params.get('q');const searchBox=document.querySelector('#search-page-input');if(searchBox&&q){searchBox.value=q;const all=[...products,...hardware.map((x,i)=>({...x,id:'hw'+i})),...peripherals.map((x,i)=>({...x,id:'per'+i}))];renderProducts(all.filter(p=>JSON.stringify(p).toLowerCase().includes(q.toLowerCase())),'#search-results')}}document.addEventListener('DOMContentLoaded',initPage);
function initProductDetail(){const el=document.querySelector('#product-detail');if(!el)return;const id=new URLSearchParams(location.search).get('id');const all=[...products,...hardware.map((x,i)=>({...x,id:'hw'+i,tag:'Hardware'})),...peripherals.map((x,i)=>({...x,id:'per'+i,tag:'Periférico'}))];const p=all.find(x=>x.id===id)||products[0];el.innerHTML=`<div class="grid grid-2"><div class="product-img" style="height:420px;border:1px solid var(--line);border-radius:18px"><div class="pc" style="transform:scale(1.5)"></div></div><div><span class="tag">${p.tag||p.cat}</span><h2>${p.name}</h2><p class="muted">Configuração/produto HyperCore desenvolvido para entregar desempenho e confiabilidade.</p><div class="price">${brl(p.price)}</div><div class="notice-list" style="margin:20px 0"><div class="notice">⚡ ${p.cpu||'Componente de alto desempenho'}</div><div class="notice">🎮 ${p.gpu||p.cat}</div><div class="notice">💾 ${p.ram||'Qualidade HyperCore'} ${p.ssd?'• '+p.ssd:''}</div></div><button class="btn primary" onclick='addCart(${JSON.stringify(p)})'>Adicionar ao carrinho</button> <a class="btn ghost" href="carrinho.html">Ver carrinho</a></div></div>`}
