from pathlib import Path
base=Path('/mnt/data/hypercore')

def shell(title,body,active=''):
    links=[('index.html','Início'),('pcs.html','PCs Gamer'),('montar.html','Monte seu PC'),('hardware.html','Hardware'),('perifericos.html','Periféricos'),('upgrades.html','Upgrades'),('servicos.html','Serviços'),('sobre.html','Sobre')]
    nav=''.join(f'<a class="{("active" if active==href else "")}" href="{href}">{label}</a>' for href,label in links)
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="HyperCore — computadores personalizados, hardware, periféricos e soluções de tecnologia."><title>{title} | HyperCore</title><link rel="stylesheet" href="styles.css"></head><body>
<div class="topbar"><div class="container"><span>⚡ Power at the Core.</span><span>Atendimento: seg–sex, 9h–18h</span></div></div>
<header class="navbar"><div class="container nav"><a class="brand" href="index.html"><img src="assets/logo.png" alt="HyperCore"><span>HYPER<b>CORE</b></span></a><button class="iconbtn mobile-toggle" onclick="document.querySelector('.navlinks').classList.toggle('mobile-open')">☰</button><nav class="navlinks">{nav}</nav><div class="nav-actions"><form id="global-search" class="search"><input class="input" style="padding:10px" placeholder="Pesquisar..." aria-label="Pesquisar"></form><a class="iconbtn" href="conta.html">👤</a><a class="iconbtn" href="carrinho.html">🛒 <span data-cart-count>0</span></a></div></div></header>
<main>{body}</main>
<footer class="footer"><div class="container footer-grid"><div><a class="brand" href="index.html"><img src="assets/logo.png" alt="HyperCore"><span>HYPER<b>CORE</b></span></a><p class="muted">Computadores personalizados, hardware e soluções de tecnologia. Você não precisa entender de hardware. Nós entendemos por você.</p></div><div><h4>Produtos</h4><a href="pcs.html">PCs Gamer</a><a href="hardware.html">Hardware</a><a href="perifericos.html">Periféricos</a><a href="montar.html">Monte seu PC</a></div><div><h4>Serviços</h4><a href="upgrades.html">Upgrades</a><a href="servicos.html">Montagem e manutenção</a><a href="garantia.html">Garantia</a><a href="suporte.html">Suporte</a></div><div><h4>HyperCore</h4><a href="sobre.html">Sobre nós</a><a href="faq.html">FAQ</a><a href="blog.html">HyperCore Lab</a><a href="contato.html">Contato</a></div></div><div class="container copyright"><span>© 2026 HyperCore. Todos os direitos reservados.</span><span>POWER AT THE CORE.</span></div></footer><div class="toast"></div><script src="app.js"></script></body></html>'''

pages={}
pages['index.html']=shell('Início', '''<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Tecnologia • Performance • Confiança</span><h1>O computador certo para o <span class="gradient">seu desempenho.</span></h1><p>A HyperCore transforma sua necessidade em uma solução completa: PCs personalizados, hardware, periféricos, upgrades e montagem profissional.</p><div class="hero-actions"><a class="btn primary" href="quiz.html">🎯 Encontre seu PC ideal</a><a class="btn ghost" href="montar.html">⚙️ Monte seu PC</a></div><div style="margin-top:22px" class="tags"><span class="tag">Compatibilidade</span><span class="tag">Custo-benefício</span><span class="tag">Suporte</span></div></div><div class="hero-media"><img src="assets/gamer.png" alt="Gamer usando computador em ambiente de alta tecnologia"></div></div></section>
<section class="section"><div class="container"><div class="section-head"><div><span class="kicker">Por que existimos</span><h2>Comprar um PC não deveria ser complicado.</h2><p>Entendemos sua necessidade antes de recomendar qualquer produto.</p></div></div><div class="grid grid-4"><div class="card feature"><div class="ico">🎯</div><div><h3>Personalização</h3><p class="muted">Configurações pensadas para seu uso e orçamento.</p></div></div><div class="card feature"><div class="ico">🔗</div><div><h3>Compatibilidade</h3><p class="muted">Peças escolhidas para trabalhar juntas.</p></div></div><div class="card feature"><div class="ico">⚙️</div><div><h3>Montagem</h3><p class="muted">Montagem, configuração e testes.</p></div></div><div class="card feature"><div class="ico">🤝</div><div><h3>Suporte</h3><p class="muted">Acompanhamento antes e depois da compra.</p></div></div></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><div><span class="kicker">Mais vendidos</span><h2>Performance HyperCore</h2><p>Escolha um ponto de partida e personalize depois.</p></div><a class="btn ghost" href="pcs.html">Ver todos</a></div><div id="pc-grid" class="grid grid-3"></div></div></section>
<section class="section"><div class="container"><div class="stats"><div class="stat"><strong>100%</strong><span>configurações personalizáveis</span></div><div class="stat"><strong>✓</strong><span>checagem de compatibilidade</span></div><div class="stat"><strong>4 níveis</strong><span>de PCs Gamer</span></div><div class="stat"><strong>Suporte</strong><span>antes e depois da compra</span></div></div></div></section>
<section class="section"><div class="container hero-mini"><div class="grid grid-2"><div><span class="kicker">Não sabe por onde começar?</span><h2>Descubra qual PC combina com você.</h2><p class="muted">Responda 3 perguntas e receba uma recomendação inicial da HyperCore.</p><a class="btn primary" href="quiz.html">Começar agora</a></div><div><div class="notice ok">✓ Uso + orçamento + upgrades → recomendação personalizada</div><div class="notice" style="margin-top:10px">💡 Você pode alterar a configuração antes de comprar.</div></div></div></div></section>''')

pages['pcs.html']=shell('PCs Gamer', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / PCs Gamer</div><h1>PCs Gamer</h1><p class="muted">Do primeiro setup ao máximo desempenho.</p></div></section><section class="section" style="padding-top:20px"><div class="container"><div class="toolbar"><input class="input search" data-filter-target="pc" placeholder="Buscar PC, processador, placa de vídeo..."><a class="btn ghost" href="comparar.html">⚖️ Comparar PCs</a><a class="btn primary" href="montar.html">⚙️ Personalizar</a></div><div id="pc-grid" class="grid grid-3"></div></div></section>''','pcs.html')

pages['hardware.html']=shell('Hardware', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Hardware</div><h1>Hardware</h1><p class="muted">Componentes para montar, atualizar e expandir seu PC.</p></div></section><section class="section" style="padding-top:20px"><div class="container"><div class="toolbar"><input class="input search" data-filter-target="hardware" placeholder="Buscar componente..."></div><div id="hardware-grid" class="grid grid-4"></div></div></section>''','hardware.html')
pages['perifericos.html']=shell('Periféricos', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Periféricos</div><h1>Periféricos</h1><p class="muted">Tudo para completar seu setup.</p></div></section><section class="section" style="padding-top:20px"><div class="container"><div class="toolbar"><input class="input search" data-filter-target="peripherals" placeholder="Buscar periférico..."></div><div id="peripheral-grid" class="grid grid-3"></div></div></section>''','perifericos.html')

pages['montar.html']=shell('Monte seu PC', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Monte seu PC</div><h1>Monte seu PC</h1><p class="muted">Escolha os componentes e veja o resumo da sua configuração.</p></div></section><section class="section" style="padding-top:15px"><div class="container"><div id="builder" class="grid"></div></div></section>''','montar.html')
pages['quiz.html']=shell('Encontre seu PC ideal', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Encontre seu PC</div><h1>Encontre seu PC ideal</h1><p class="muted">Responda algumas perguntas para receber uma recomendação inicial.</p></div></section><section class="section" style="padding-top:20px"><div class="container"><div id="quiz" class="wizard"><div id="quiz-steps" class="steps"></div><div class="card wizard-panel"><div id="quiz-content"></div></div></div></div></section>''')

pages['upgrades.html']=shell('Upgrades', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Upgrades</div><h1>Seu PC pode melhorar.</h1><p class="muted">Nem sempre você precisa comprar um computador novo.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><div class="card"><span class="kicker">Diagnóstico</span><h2>Conte como está seu computador.</h2><form id="upgrade-form"><div class="form-grid"><div><label class="label">Processador</label><input class="input" required placeholder="Ex.: Ryzen 5 3600"></div><div><label class="label">Placa de vídeo</label><input class="input" placeholder="Ex.: RTX 3060"></div><div><label class="label">RAM</label><input class="input" placeholder="Ex.: 16 GB"></div><div><label class="label">Armazenamento</label><input class="input" placeholder="Ex.: SSD 480 GB"></div><div class="full"><label class="label">O que você quer melhorar?</label><select class="select"><option>Jogos / FPS</option><option>Inicialização e velocidade</option><option>Edição e criação</option><option>Uso geral</option></select></div></div><button class="btn primary" style="margin-top:16px">Analisar configuração</button></form></div><div id="upgrade-result" class="card"><span class="kicker">Dica HyperCore</span><h2>Upgrade certo, gasto inteligente.</h2><p class="muted">Preencha os dados para receber uma análise preliminar.</p></div></div></section>''','upgrades.html')

pages['servicos.html']=shell('Serviços', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Serviços</div><h1>Serviços HyperCore</h1><p class="muted">Tecnologia não termina na compra.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-3"><div class="card"><div class="feature"><div class="ico">⚙️</div><div><h3>Montagem profissional</h3><p class="muted">Montagem, organização, configuração e testes.</p></div></div></div><div class="card"><div class="feature"><div class="ico">🧹</div><div><h3>Manutenção</h3><p class="muted">Limpeza e manutenção preventiva do equipamento.</p></div></div></div><div class="card"><div class="feature"><div class="ico">🔧</div><div><h3>Upgrade</h3><p class="muted">Identificação e substituição de componentes.</p></div></div></div><div class="card"><div class="feature"><div class="ico">💻</div><div><h3>Configuração</h3><p class="muted">Sistema, drivers e ajustes iniciais.</p></div></div></div><div class="card"><div class="feature"><div class="ico">🩺</div><div><h3>Diagnóstico</h3><p class="muted">Análise de problemas e recomendações.</p></div></div></div><div class="card"><div class="feature"><div class="ico">🎮</div><div><h3>Otimização</h3><p class="muted">Ajustes para jogos e aplicações.</p></div></div></div></div></div></section>''','servicos.html')

pages['sobre.html']=shell('Sobre nós', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Sobre</div><h1>Sobre a HyperCore</h1><p class="muted">Power at the Core.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><div class="card"><span class="kicker">O projeto</span><h2>Mais que uma loja de PCs.</h2><p class="muted">A HyperCore é uma empresa especializada em computadores, componentes, periféricos e soluções de tecnologia. Nosso projeto nasceu para resolver uma dificuldade comum: escolher, montar e melhorar um computador sem precisar ser especialista em hardware.</p><p class="muted">Nossa função é entender a necessidade do cliente e transformar orçamento, uso e objetivo em uma solução adequada.</p></div><div class="card"><span class="kicker">Nossa promessa</span><h2>Você não precisa entender de hardware. Nós entendemos por você.</h2><p class="muted">Transparência, compatibilidade, custo-benefício, qualidade e suporte fazem parte da experiência HyperCore.</p></div></div></section><section class="section alt"><div class="container grid grid-3"><div class="card"><h3>🎯 Missão</h3><p class="muted">Facilitar o acesso à tecnologia com soluções personalizadas.</p></div><div class="card"><h3>🚀 Visão</h3><p class="muted">Ser referência em computadores personalizados e soluções de tecnologia.</p></div><div class="card"><h3>💙 Valores</h3><p class="muted">Qualidade, transparência, inovação, confiança e desempenho.</p></div></div></section>''','sobre.html')

pages['blog.html']=shell('HyperCore Lab', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / HyperCore Lab</div><h1>HyperCore Lab</h1><p class="muted">Conteúdo para você entender melhor tecnologia.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-3"><article class="card"><span class="tag">Hardware</span><h3>16 GB ou 32 GB de RAM?</h3><p class="muted">Entenda quando mais memória realmente faz diferença.</p><button class="btn ghost" onclick="openModal('#article-modal')">Ler artigo</button></article><article class="card"><span class="tag">GPU</span><h3>Como escolher uma placa de vídeo?</h3><p class="muted">Veja os pontos que importam antes de comprar.</p><button class="btn ghost" onclick="openModal('#article-modal')">Ler artigo</button></article><article class="card"><span class="tag">PC</span><h3>SSD NVMe vale a pena?</h3><p class="muted">Entenda as diferenças entre armazenamento.</p><button class="btn ghost" onclick="openModal('#article-modal')">Ler artigo</button></article></div></section><div id="article-modal" class="modal"><div class="modal-box"><div class="modal-head"><h2>HyperCore Lab</h2><button class="iconbtn" onclick="closeModal('#article-modal')">✕</button></div><p class="muted">Este espaço pode receber artigos completos, comparativos, guias de compra e notícias da HyperCore.</p><div class="notice ok">Conteúdo demonstrativo do protótipo.</div></div></div>''','blog.html')

pages['faq.html']=shell('FAQ', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / FAQ</div><h1>Perguntas frequentes</h1></div></section><section class="section" style="padding-top:15px"><div class="container card faq"><details open><summary>A HyperCore monta computadores personalizados?</summary><p class="muted">Sim. O cliente pode escolher uma configuração ou solicitar uma recomendação.</p></details><details><summary>Posso escolher todas as peças?</summary><p class="muted">Sim. O configurador permite montar uma configuração e revisar os componentes.</p></details><details><summary>Vocês fazem upgrades?</summary><p class="muted">Sim. A proposta inclui análise do equipamento e indicação de possíveis melhorias.</p></details><details><summary>Como funciona a compatibilidade?</summary><p class="muted">O projeto prevê uma verificação dos componentes escolhidos antes da compra.</p></details><details><summary>Posso comprar apenas peças?</summary><p class="muted">Sim. A loja possui categorias de hardware e periféricos.</p></details><details><summary>O pagamento é real?</summary><p class="muted">Neste protótipo, o checkout é demonstrativo. Um projeto real precisaria de integração com um gateway de pagamento e backend.</p></details></div></section>''','faq.html')

pages['garantia.html']=shell('Garantia', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Garantia</div><h1>Garantia e políticas</h1><p class="muted">Transparência faz parte da HyperCore.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><div class="card"><h3>🛡️ Garantia</h3><p class="muted">Produtos e serviços devem seguir os prazos e condições definidos pela empresa e pelos fabricantes.</p></div><div class="card"><h3>↩️ Trocas e devoluções</h3><p class="muted">A página pode detalhar prazos, condições e procedimentos conforme a política comercial.</p></div><div class="card"><h3>🔧 Montagem</h3><p class="muted">Registre o serviço, os testes realizados e a configuração entregue ao cliente.</p></div><div class="card"><h3>📞 Atendimento</h3><p class="muted">Em caso de problema, o cliente pode abrir uma solicitação de suporte.</p></div></div></section>''','garantia.html')

pages['suporte.html']=shell('Suporte', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Suporte</div><h1>Suporte HyperCore</h1><p class="muted">Conte o que aconteceu. Vamos direcionar sua solicitação.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><form class="card" onsubmit="event.preventDefault();toast('Chamado aberto com sucesso!')"><div class="form-grid"><div><label class="label">Nome</label><input class="input" required></div><div><label class="label">E-mail</label><input class="input" type="email" required></div><div><label class="label">Tipo</label><select class="select"><option>Problema técnico</option><option>Pedido</option><option>Upgrade</option><option>Montagem</option><option>Garantia</option></select></div><div><label class="label">Número do pedido</label><input class="input" placeholder="HC12345"></div><div class="full"><label class="label">Mensagem</label><textarea class="textarea" rows="6" required></textarea></div></div><button class="btn primary">Enviar chamado</button></form><div class="card"><h3>Atendimento</h3><div class="notice-list"><div class="notice">💬 WhatsApp — resposta rápida</div><div class="notice">✉️ suporte@hypercore.local</div><div class="notice">🕘 Segunda a sexta — 9h às 18h</div></div></div></div></section>''','suporte.html')

pages['contato.html']=shell('Contato', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Contato</div><h1>Fale com a HyperCore</h1></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><div class="card"><h2>Vamos encontrar sua solução.</h2><p class="muted">Entre em contato para orçamento, montagem, upgrades ou dúvidas.</p><div class="notice-list"><div class="notice">📱 WhatsApp: (11) 99999-9999</div><div class="notice">✉️ contato@hypercore.local</div><div class="notice">📸 Instagram: @hypercore</div></div></div><form class="card" onsubmit="event.preventDefault();toast('Mensagem enviada para a HyperCore!')"><label class="label">Nome</label><input class="input" required><label class="label" style="margin-top:14px">E-mail</label><input class="input" type="email" required><label class="label" style="margin-top:14px">Mensagem</label><textarea class="textarea" rows="6" required></textarea><button class="btn primary" style="margin-top:14px">Enviar mensagem</button></form></div></section>''','contato.html')

pages['conta.html']=shell('Minha conta', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Minha conta</div><h1>Minha conta</h1><p class="muted">Área demonstrativa do cliente.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><form class="card" onsubmit="event.preventDefault();toast('Login demonstrativo realizado!')"><h2>Entrar</h2><label class="label">E-mail</label><input class="input" type="email" required><label class="label" style="margin-top:14px">Senha</label><input class="input" type="password" required><button class="btn primary" style="margin-top:16px;width:100%">Entrar</button></form><form class="card" onsubmit="event.preventDefault();toast('Conta demonstrativa criada!')"><h2>Criar conta</h2><label class="label">Nome</label><input class="input" required><label class="label" style="margin-top:14px">E-mail</label><input class="input" type="email" required><label class="label" style="margin-top:14px">Senha</label><input class="input" type="password" required><button class="btn ghost" style="margin-top:16px;width:100%">Criar conta</button></form></div></section>''','conta.html')

pages['carrinho.html']=shell('Carrinho', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Carrinho</div><h1>Seu carrinho</h1></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><div class="card"><div id="cart-items"></div></div><div id="cart-summary"></div></div></section>''')
pages['checkout.html']=shell('Checkout', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Checkout</div><h1>Finalizar pedido</h1><p class="muted">Protótipo de checkout — sem cobrança real.</p></div></section><section class="section" style="padding-top:15px"><div class="container grid grid-2"><form id="checkout-form" class="card"><h2>Dados do pedido</h2><div class="form-grid"><div><label class="label">Nome completo</label><input class="input" required></div><div><label class="label">E-mail</label><input class="input" type="email" required></div><div class="full"><label class="label">Endereço</label><input class="input" required></div><div><label class="label">CEP</label><input class="input" required></div><div><label class="label">Forma de pagamento</label><select class="select"><option>PIX — demonstração</option><option>Cartão — demonstração</option></select></div></div><button class="btn primary" style="margin-top:18px">Confirmar pedido</button></form><div class="card"><span class="kicker">Resumo</span><h2>Total</h2><div id="checkout-total" class="price">R$ 0,00</div><p class="muted">Os valores são demonstrativos.</p></div></div><div id="checkout-success" class="container hidden" style="margin-top:20px"><div class="result"><h2>Pedido recebido! 🎉</h2><p class="muted">Seu pedido foi registrado no protótipo. Em uma versão real, aqui entrariam pagamento, estoque e rastreamento.</p><a class="btn primary" href="index.html">Voltar para a Home</a></div></div></section>''')
pages['comparar.html']=shell('Comparar PCs', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Comparar</div><h1>Compare configurações</h1><p class="muted">Veja rapidamente as diferenças entre os principais PCs.</p></div></section><section class="section" style="padding-top:15px"><div class="container card"><table class="compare-table"><thead><tr><th>Especificação</th><th>Starter</th><th>Pro</th><th>Elite</th><th>Extreme</th></tr></thead><tbody><tr><td>CPU</td><td>Ryzen 5 5600G</td><td>Ryzen 5 7600</td><td>Ryzen 7 7800X3D</td><td>Ryzen 9 9950X3D</td></tr><tr><td>GPU</td><td>Integrada</td><td>RTX 5060</td><td>RTX 5070</td><td>RTX 5090</td></tr><tr><td>RAM</td><td>16 GB</td><td>16 GB DDR5</td><td>32 GB DDR5</td><td>64 GB DDR5</td></tr><tr><td>SSD</td><td>500 GB</td><td>1 TB</td><td>2 TB</td><td>4 TB</td></tr><tr><td>Preço</td><td>${'{'}products[0].price{'}'}</td><td>R$ 4.499</td><td>R$ 6.999</td><td>R$ 11.999</td></tr></tbody></table></div></section>''')
pages['buscar.html']=shell('Busca', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Busca</div><h1>Resultados</h1><input id="search-page-input" class="input search" placeholder="Pesquisar..."></div></section><section class="section" style="padding-top:15px"><div class="container"><div id="search-results" class="grid grid-3"></div></div></section>''')
pages['produto.html']=shell('Produto', '''<section class="page-hero"><div class="container"><div class="breadcrumbs">Início / Produto</div><h1>Detalhes do produto</h1></div></section><section class="section" style="padding-top:15px"><div class="container"><div id="product-detail" class="card"></div></div></section>''')

for name,content in pages.items(): (base/name).write_text(content,encoding='utf-8')
